- name: Reload systemd
  become: yes
  command: systemctl daemon-reload

- name: Restart gunicorn
  become: true
  service:
    name: exonviz
    state: restarted

- name: Restart nginx
  become: true
  service:
    name: nginx
    state: restarted
