- name: Install packages
  become: yes
  apt:
    name:
      - acl
      - git
      - nginx
    state: present

- name: Set timezone
  become: yes
  community.general.timezone:
    name: Europe/Brussels

- name: Create dcrt user
  become: yes
  ansible.builtin.user:
    name: "{{ user }}"

- name: Remove default nginx site
  become: yes
  ansible.builtin.file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: Configure logrotate for nginx
  become: yes
  ansible.builtin.lineinfile:
    path: /etc/logrotate.d/nginx
    regexp: "\tdaily$"
    line: "\tyearly"

- name: Disable HTTP compression for nginx
  become: yes
  ansible.builtin.lineinfile:
    path: /etc/nginx/nginx.conf
    regexp: "\tgzip on;"
    line: "\tgzip off;"
