- name: Reload systemd
  become: yes
  command: systemctl daemon-reload

- name: Restart gunicorn
  become: true
  service:
    name: "{{ project }}"
    state: restarted

- name: Restart nginx
  become: true
  service:
    name: nginx
    state: restarted

- name: Restart gtgt
  become: true
  service:
    name: gtgt
    start: restarted
